modLoader="javafml"
loaderVersion="[21.1,)"
license="MIT"

[[mods]]
modId="ucg"
version="${file.jarVersion}"
displayName="Urceus Command Generator"
description="Client-side command generator"
authors="Urceus"

[[dependencies.ucg]]
modId="neoforge"
mandatory=true
versionRange="[21.1,)"
ordering="NONE"
side="CLIENT"

[[dependencies.ucg]]
modId="minecraft"
mandatory=true
versionRange="[1.21.1,1.21.2)"
ordering="NONE"
side="CLIENT"